//Action types for a API call
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

//for multiple API Calls
export const FETCHING_DATA_MULTIPLE = 'FETCHING_DATA_MULTIPLE';
export const FETCHING_DATA_SUCCESS_MULTIPLE = 'FETCHING_DATA_SUCCESS_MULTIPLE';
export const FETCHING_DATA_FAILURE_MULTIPLE = 'FETCHING_DATA_FAILURE_MULTIPLE';


////For map
export const FETCHING_DATA_MAP = 'FETCHING_DATA_MAP';
export const FETCHING_DATA_SUCCESS_MAP = 'FETCHING_DATA_SUCCESS_MAP';
export const FETCHING_DATA_FAILURE_MAP = 'FETCHING_DATA_FAILURE_MAP';


export const FETCHING_DATA_OTHER = 'FETCHING_DATA_OTHER';
export const FETCHING_DATA_SUCCESS_OTHER = 'FETCHING_DATA_SUCCESS_OTHER';
export const FETCHING_DATA_FAILURE_OTHER = 'FETCHING_DATA_FAILURE_OTHER';

export const REQUEST_LOADER = 'REQUEST_LOADER';
export const FINISH_LOADER = 'FINISH_LOADER';

export const RESET = 'RESET';
export const RESET_OTHER_DATA = 'RESET_OTHER_DATA';

export const SETTING_THEME = 'SETTING_THEME';

